### DISCUSSION TITLE
How to reference values from other fields

### DISCUSSION THREAD

**Discussion by Mrahmani71** [Thinkmill/keystatic#1317] [Q&A]
Hi, I have frontmatter in my project that looks like this:
```
---
title: xxx
description: xxx
meta:
    meta_title: xxx
    meta_description: xxxx
---
```
Currently, the meta_title has the same value as title, and meta_description has the same value as description.
Is it possible to automatically set the value of meta_title to match title, and meta_description to match description when I create a new post? This way, I would only need to fill in title and description, and the meta fields would be populated automatically.
Thanks!
